### ISSUE TITLE
Does browserify browserify itself?

### ISSUE THREAD

**Issue by chevett** [hughsk/disc#28]
cool tool!

http://bl.ocks.org/chevett/raw/517c9c476fab01b058b5/

Am I reading this correctly?  The top left quadrant is mostly browserify?  Which in turn is mostly crypto-browserify?  What??  Maybe this is expected and I just never realized it?

**Comment by hughsk** [comment]
@chevett thanks!

Whoa, that's a lot of extra files. That quadrant is mostly browserify, but only its browser shims for `readable-stream` and `crypto`. Unfortunately disc isn't highlighting those as part of a browserify core (which is a bug), but I suspect most of those files are coming from a module that's using `require('crypto')` somewhere. You might want to check the `uuid` module and make sure that it's still using `rng-browser.js` instead of `rng.js` when being bundled with browserify if you're looking to reduce your bundle size :)

**Comment by chevett** [comment]
That was immensely helpful!  `uuid` was doing it and removing it reduced the bundle size by nearly half a mb.  Thank you!!! :+1: :+1: :+1:
